FROM python:3.13-slim
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg nodejs curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN python -m pip install --no-cache-dir --upgrade pip --root-user-action=ignore \
    && pip install --no-cache-dir --disable-pip-version-check --root-user-action=ignore -r requirements.txt

COPY fetcher.py .
COPY start.sh .
CMD ["./start.sh"]
