FROM debian:trixie-slim
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /usr/src

ENV PULSE_SERVER=tcp:localhost:4317

RUN apt-get update && apt-get install -y --no-install-recommends \
    gmediarender \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-pulseaudio \
  && rm -rf /var/lib/apt/lists/*

COPY start.sh /usr/src/

CMD [ "/bin/bash", "/usr/src/start.sh" ]
